# Generated by Django 3.2.25 on 2024-09-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_status', models.CharField(choices=[('InProgress', 'In Progress'), ('LOST', 'Lost'), ('WON', 'Won')], default='InProgress', max_length=10)),
                ('word', models.CharField(max_length=100)),
                ('guessed_letters', models.TextField(default='')),
                ('incorrect_guesses', models.IntegerField(default=0)),
                ('max_incorrect_guess', models.IntegerField()),
            ],
        ),
    ]
