# Generated by Django 3.2.25 on 2024-09-15 11:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('guess_word_game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
